# Add 'type: documentation' label to any changes in docs folder
"type: documentation":
  - docs/**/*
  - "**/*.md"

# Add 'type: dependencies' to any changes in go.mod or go.sum
"type: dependencies":
  - go.mod
  - go.sum

# Add 'scope: tests' to any changes in test files
"scope: tests":
  - "**/*_test.go"

# Add 'scope: ci' to any changes in GitHub workflows
"scope: ci":
  - .github/workflows/**/*

# Add size labels based on changes
"size: XS":
  - size-below: 10
  - size-above: 0

"size: S":
  - size-below: 30
  - size-above: 10
  - all: ["!size: XS"]

"size: M":
  - size-below: 100
  - size-above: 30
  - all: ["!size: XS", "!size: S"]

"size: L":
  - size-below: 500
  - size-above: 100
  - all: ["!size: XS", "!size: S", "!size: M"]

"size: XL":
  - size-above: 500
  - all: ["!size: XS", "!size: S", "!size: M", "!size: L"]
