"type: documentation":
  - changed-files:
    - any-glob-to-any-file: ["docs/**/*", "**/*.md"]

"type: dependencies":
  - changed-files:
    - any-glob-to-any-file: ["go.mod", "go.sum"]

"scope: tests":
  - changed-files:
    - any-glob-to-any-file: ["**/*_test.go"]

"scope: ci":
  - changed-files:
    - any-glob-to-any-file: [".github/workflows/**/*"]

"size: XS":
  - size-below: 10
"size: S":
  - size-above: 10
  - size-below: 30
"size: M":
  - size-above: 30
  - size-below: 100
"size: L":
  - size-above: 100
  - size-below: 500
"size: XL":
  - size-above: 500
