# Type labels
"type: documentation":
  - any: ["docs/**/*", "**/*.md"]

"type: dependencies":
  - any: ["go.mod", "go.sum"]

"scope: tests":
  - any: ["**/*_test.go"]

"scope: ci":
  - any: [".github/workflows/**/*"]
