# Priority Labels
- name: "priority: critical"
  color: "b60205"
  description: "Requires immediate attention"
- name: "priority: high"
  color: "d93f0b"
  description: "Requires attention soon"
- name: "priority: medium"
  color: "fbca04"
  description: "Normal priority"
- name: "priority: low"
  color: "0e8a16"
  description: "Can be addressed later"

# Type Labels
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "type: feature"
  color: "0075ca"
  description: "New feature request"
- name: "type: improvement"
  color: "a2eeef"
  description: "Improvement to existing features"
- name: "type: documentation"
  color: "0075ca"
  description: "Documentation changes"
- name: "type: security"
  color: "d93f0b"
  description: "Security related changes"
- name: "type: dependencies"
  color: "0366d6"
  description: "Dependencies updates"

# Status Labels
- name: "status: blocked"
  color: "d73a4a"
  description: "Blocked by other work"
- name: "status: in-progress"
  color: "fbca04"
  description: "Currently being worked on"
- name: "status: ready-for-review"
  color: "0e8a16"
  description: "Ready for review"
- name: "status: needs-review"
  color: "fbca04"
  description: "Needs code review"
- name: "status: needs-testing"
  color: "fbca04"
  description: "Needs testing"

# Size Labels
- name: "size: XS"
  color: "91ca55"
  description: "Extra small changes"
- name: "size: S"
  color: "c2e0c6"
  description: "Small changes"
- name: "size: M"
  color: "fbca04"
  description: "Medium changes"
- name: "size: L"
  color: "eb6420"
  description: "Large changes"
- name: "size: XL"
  color: "b60205"
  description: "Extra large changes"

# Scope Labels
- name: "scope: core"
  color: "5319e7"
  description: "Core functionality changes"
- name: "scope: tests"
  color: "fbca04"
  description: "Test related changes"
- name: "scope: ci"
  color: "0075ca"
  description: "CI/CD related changes"
- name: "scope: security"
  color: "d93f0b"
  description: "Security related changes"

# Additional Labels
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention needed"
- name: "invalid"
  color: "e4e669"
  description: "Invalid issue or PR"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or PR already exists"
