linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  varnamelen:
    min-name-length: 1
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - gosimple
  disable:
    - gochecknoglobals
    - wsl
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - mnd

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec