name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

if: |
  !contains(github.event.head_commit.message, '[skip ci]') &&
  !contains(github.event.head_commit.message, '[ci skip]') &&
  !contains(github.event.head_commit.message, '[no ci]') &&
  !contains(github.event.head_commit.message, '[skip actions]') &&
  !contains(github.event.head_commit.message, '[actions skip]')

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write

jobs:
  should-skip:
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.skip-check.outputs.should_skip }}
    steps:
      - id: skip-check
        uses: actions/github-script@v7
        with:
          script: |
            const message = context.payload.head_commit?.message || '';
            const skipPatterns = [
              '[skip ci]',
              '[ci skip]',
              '[no ci]',
              '[skip actions]',
              '[actions skip]'
            ];
            const shouldSkip = skipPatterns.some(pattern => message.includes(pattern)) ||
              message.startsWith('docs:') ||
              message.startsWith('style:') ||
              message.startsWith('chore(docs):');
            core.setOutput('should_skip', shouldSkip);
            
  verify:
    needs: should-skip
    if: ${{ needs.should-skip.outputs.should-skip != 'true' }}
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Verify dependencies
        run: go mod verify
      
      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

  lint:
    needs: should-skip
    if: ${{ needs.should-skip.outputs.should-skip != 'true' }}
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          
      - name: Check formatting
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted correctly:"
            gofmt -l .
            exit 1
          fi
          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m
          only-new-issues: true

  security:
    needs: should-skip
    if: ${{ needs.should-skip.outputs.should-skip != 'true' }}
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt=sarif -out=security-results.sarif ./...'
      
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          
      - name: Upload security results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: security-results.sarif
          category: security-scan

  labeler:
    needs: [should-skip, verify, lint, security]
    if: ${{ needs.should-skip.outputs.should-skip != 'true' }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: false
    
  skipped:
    needs: should-skip
    if: ${{ needs.should-skip.outputs.should-skip == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI
        run: |
          echo "CI skipped due to commit message"
          exit 0
